### ISSUE TITLE
Validation fails for plugins with required params

### ISSUE THREAD

**Issue by singhsaban** [matcha440/express-gateway-test-tools#5]
When trying to run tests on plugins with required parameters it errors out. I think this is because of a recent validation check before loading plugins https://github.com/ExpressGateway/express-gateway/pull/757. But we don't specify any params when creating gateway in create-gateway.js.

`config.systemConfig = {
      plugins: {
        'custom-plugin': {
          package: pluginPackage,
          'param' : 'param1'
        }
      }
    };`

**Comment by matcha440** [comment]
@singhsaban thanks for bringing this to my attention.  I'll be looking into this as soon as I can.

**Comment by matcha440** [comment]
Released with `v0.3.0`, closing this one out.
