### ISSUE TITLE
Usage Examples in readme.md

### ISSUE THREAD

**Issue by roarbb** [matcha440/express-gateway-test-tools#8]
Not sure if this library is intended for public to use, but the example could be better. Right now there are few issues like:

`[
    param1: 'foo',
    param2: 'bar'
]` is not really a valid array, is it?

Also the `request` is not defined.

**Comment by matcha440** [comment]
Yeah in that example it shouldn't be an array, I will fix that up.  I'll also try to make the example look a bit more complete.

**Comment by matcha440** [comment]
> Not sure if this library is intended for public to use,...
> 

If I hadn't intended it for the public, I would've made it private.  I want others to potentially benefit from the patterns I've used in the past, or give feedback to help improve those things.  So thank you for doing just that.  😃

**Comment by roarbb** [comment]
Thanks for the response, I have a working example now! Couldn't figure out that you're using supertest package there :)
